### PR TITLE
Create selectionsort.cpp

### PR DESCRIPTION
**Pull request by VanshMishra**

### CODE REVIEW

**Comment by 3NCRY9T3R** [comment]
Put the file under the folder.

**Comment by VanshMishra** [comment]
How?

**Comment by VanshMishra** [comment]
Done...Please check.

Put the file under the folder.

**Comment by 3NCRY9T3R** [comment]
Wrong folder.

**Comment by VanshMishra** [comment]
Sir plz Check Again

**Comment by 3NCRY9T3R** [comment]
You deleted the file.

**Pull request closed without merging**
